{{- if .Values.postgres.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "fluxer.pgClusterName" . }}
  labels:
    {{- include "fluxer.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  instances: {{ .Values.postgres.instances }}
  {{- with .Values.postgres.imageName }}
  imageName: {{ . }}
  {{- end }}
  bootstrap:
    initdb:
      database: {{ .Values.postgres.database }}
      owner: {{ .Values.postgres.owner }}
  storage:
    size: {{ .Values.postgres.storage.size }}
    {{- with .Values.postgres.storage.storageClass }}
    storageClass: {{ . }}
    {{- end }}
  {{- if .Values.postgres.walStorage.enabled }}
  walStorage:
    size: {{ .Values.postgres.walStorage.size }}
    {{- with .Values.postgres.walStorage.storageClass }}
    storageClass: {{ . }}
    {{- end }}
  {{- end }}
  {{- with .Values.postgres.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.postgres.parameters }}
  postgresql:
    parameters:
      {{- toYaml .Values.postgres.parameters | nindent 6 }}
  {{- end }}
  {{- with .Values.postgres.extraSpec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
